{{- if or ( and ( .Values.app.ssl.key ) ( .Values.app.ssl.cert )) ( .Values.app.ssl.k8sCerts ) }}
{{- $type := "sec" -}}
{{- $action := "tls" -}}
{{- $Name := include "passbolt-library.fullname" . -}}
{{- $fullName := printf "%s-%s-%s" $Name $type $action -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "passbolt-library.labels" . | nindent 4 }}
    {{- include "passbolt-library.selectorLabels" . | nindent 4 }}
    {{- include "passbolt-library.typelabels" (dict "action" $action "type" $type) | nindent 4 }}
type: Opaque
data:
{{- if and ( .Values.app.ssl.key ) ( .Values.app.ssl.cert ) }}
  tls.crt: {{ .Values.app.ssl.cert }}
  tls.key: {{ .Values.app.ssl.key }}
{{- else }}
{{- if and ( not .Values.app.ssl.key ) ( not .Values.app.ssl.cert ) ( .Values.app.ssl.k8sCerts ) }}
{{ ( include "passbolt-library.gen-certs" . ) | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
